### ISSUE TITLE
The Plugin is converting Microsoft Project files into Word Docs for some reason? and the file is broken.

### ISSUE THREAD

**Issue by jadams-rva** [Blobfolio/righteous-mimes#7]
VALIDATION:
  Naive Name: Schedule Template_MS Project Version-Architecture.mpp
  Naive Extension: mpp
  Naive Type: application/msproject
  Magic Type: application/vnd.ms-office
  Best Type: application/msword

FINAL:
  Name: Schedule Template_MS Project Version-Architecture.doc
  Extension: doc
  Type: application/msword
  Code: 75

SYSTEM:
  Kernel: Linux c118312.sgvps.net 3.12.18-clouder0 #3 SMP PREEMPT Wed May 25 12:13:20 EEST 2022 x86_64
  PHP: 7.4.33
  Modules: Core; PDO; Phar; Reflection; SPL; SimpleXML; Zend OPcache; apache2handler; bcmath; bz2; calendar; ctype; curl; date; dba; dom; enchant; exif; fileinfo; filter; ftp; gd; gettext; gmp; hash; iconv; imap; intl; json; libxml; mbstring; memcached; mysqli; mysqlnd; openssl; pcre; pdo_mysql; pdo_pgsql; pdo_sqlite; pgsql; posix; pspell; session; shmop; soap; sockets; sodium; sqlite3; standard; sysvmsg; sysvsem; tidy; tokenizer; xml; xmlreader; xmlrpc; xmlwriter; xsl; zip; zlib
  WordPress: 6.2.2
  Plugins: acf [6.1.6]; blob-mimes [1.3.14]; classic-editor [1.6.3]; custom-post-type-ui [1.13.6]; happy-scss-compiler [1.3.10]; relevanssi [2.23.0]; sg-cachepress [7.3.2]; sg-security [1.4.5]; user-role-editor [4.63.3]; wp-crontrol [1.15.2]; wpo365-login [23.0]; wpo365-login-premium [23.0]
  Theme: toolbox [1.0.0]

**Comment by joshstoik1** [comment]
Thanks for the report @jadams-rva!

I just pushed a new release of `Lord of the Files` (`1.3.16`) with a workaround for MS Office Project files. Once your site sees the change, would you please update the plugin, then re-upload the failing file(s) to see if they come through okay now?

The MIME type will probably still be misidentified because `mpp` is used by multiple programs for completely different things, but office variants should now be recognized, preventing any extension-swapping.

I'll leave the ticket open in the meantime, just in case.

Thanks again!

**Comment by jadams-rva** [comment]
Thank you so much for solving this issue.
Everything seems fine now.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by joshstoik1** [comment]
Thanks for confirming, @jadams-rva!

If you stumble across any other random file weirdness down the road, just let me know.
